### ISSUE TITLE
Can't package examples - "cannot initialize module Header - unable to load header file config/java.header"

### ISSUE THREAD

**Issue by yukaReal** [FINRAOS/DataGenerator#109]
mvn package
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.343s
[INFO] Finished at: Fri Aug 15 01:56:37 EDT 2014
[INFO] Final Memory: 28M/183M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.12.1:check (test) on project dg-example-default: Failed during checkstyle configuration: cannot initialize module Header - unable to load header file config/java.header -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
yuriy@bigbrother:/media/th/warehouse/projects/DataGenerator/dg-example-default$

**Comment by apeshave** [comment]
I am having the same issue. It's getting routed to gradle folder for some reason.
`Caused by: java.io.FileNotFoundException: /Users/adityapeshave/.gradle/daemon/4.10/config/central.header (No such file or directory)
        at com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck.loadHeaderFile(AbstractHeaderCheck.java:117)
        ... 80 more
`

**Comment by mibrahim** [comment]
@apeshave - can you describe what were you attempting to do? were you just attempting to compile?

**Comment by apeshave** [comment]
Just compile. Specifically Checkstype goal.
`> Task :compileJava
Note: /Users/XXX/XXX/XXXXImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleMain'.
> Unable to create a Checker: cannot initialize module RegexpHeader - unable to load header file config/central.header

`
