### ISSUE TITLE
We need a way of processing muplitple input scxml files through one run

### ISSUE THREAD

**Issue by yukaReal** [FINRAOS/DataGenerator#150]
In real life we need to generate multiple data files for one system.
Now we can do it by configuring multiple scxml files and run DG correspondent number of times.
IMHO, it's ok for multithread version of DG (it's cheap to start / stop it), but it's expansive (from time point of view) for hadoop version.

So, IMHO, it will be good to have a feature to be able to run DG and configure to process multiple scxml files by single run (and produce multiple output files).

**Comment by mibrahim** [comment]
implemented by #191
