### ISSUE TITLE
Cannot have a comma(,) within dg:assign set attribute

### ISSUE THREAD

**Issue by wnilkamal** [FINRAOS/DataGenerator#166]
WORKS
\<dg:assign name="var_out_V3" set="%ssn,%currency,%regex([0-9]{3}[A-Z0-9]{5}),%number(3)"/>

DOESN'T WORK
\<dg:assign name="var_out_V3" set="%ssn,%currency,%regex([0-9]{3}[A-Z0-9]{5}),%number(3,2)"/>

The following exception is thrown to the user in this case
Exception in thread "Thread-28" java.lang.NumberFormatException: For input string: ""

**Comment by mibrahim** [comment]
implemented in #190
