### ISSUE TITLE
Need to update doc links at http://finraos.github.io/DataGenerator/

### ISSUE THREAD

**Issue by yukaReal** [FINRAOS/DataGenerator#198]
Now link don't work...
![snip20150206_7](https://cloud.githubusercontent.com/assets/4859112/6087373/8eb2e126-ae18-11e4-8ef7-3d844620beba.png)

Old link:
* https://github.com/FINRAOS/DataGenerator#quick-start
* http://finraos.github.io/DataGenerator/docs/html/BasicExample.html

**Comment by bryantrobbins** [comment]
Java API Docs for 2.1 should be at http://finraos.github.io/DataGenerator/apis/v2.1/index.html (this link currently does not exist).

We also need to do the same for 2.2 as part of that version's release.

**Comment by mibrahim** [comment]
Fixed by #245
