### ISSUE TITLE
GDG Backend API Development

### ISSUE THREAD

**Issue by bryantrobbins** [FINRAOS/DataGenerator#207]
We need a backend API server which processes requests from the client. It should compile to a WAR file for deployment in a simple Apache Tomcat instance.

Available calls:
* generateData() - takes in data json, spins up worker for doing generation, returns id (async)
* getGenerationStatus() - takes in id, returns current data size
* getLinksForSession() - takes in unique session id, returns list of links for the session

**Comment by mibrahim** [comment]
@m-dub and @mibrahim

**Comment by mibrahim** [comment]
Using spring boot seems a good choice for a self contained container ( http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started ), however, it also seems that we cannot package the project as a war if decide later to deploy in a separate container.

**Comment by bryantrobbins** [comment]
I believe building a war is also possible with Boot with some minimal changes: http://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html
