### ISSUE TITLE
Need to push dg-parent 2.1 to Maven Central

### ISSUE THREAD

**Issue by bryantrobbins** [FINRAOS/DataGenerator#212]
Currently, it's not possible to include the 2.1 resource in the pom of another project, as dg-parent 2.1 isn't pushed to Maven Central. See the list of org.finra.datagenerator artifacts here:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.finra.datagenerator%22

**Comment by bryantrobbins** [comment]
We fixed this at Bitcamp.

2.1 of dg-parent now sync'ed with Central:
https://repo1.maven.org/maven2/org/finra/datagenerator/dg-parent/2.1/

**Comment by wnilkamal** [comment]
Nice!
