### ISSUE TITLE
Custom Writers (CSV, JSON, SQL, XML, etc)

### ISSUE THREAD

**Issue by mauricio1990silva** [FINRAOS/DataGenerator#213]
DataGen should  be able at least to export the final output as CSV, JSON, SQL, XML, etc, chosen by the user

**Comment by bryantrobbins** [comment]
@mauricio1990silva how is this going? Please feel free to send a PR.

**Comment by mibrahim** [comment]
As a thought, I propose looking at webhdfs and writing an output stream wrapper to it.

**Comment by mibrahim** [comment]
@mauricio1990silva, @bryantrobbins  and Andriy is looking at this.

**Comment by bryantrobbins** [comment]
Discussed this today, and decided to add an interface like this to dg-commons:

interface DataWriter<T>:
  void pre()
  void writeOutput(T)
  void post()

For example, the current DefaultWriter:

DefaultWriter implements DataWriter<Map<String, String>>:

  void writeOutput(Map<String, String> data):
    data.getKey()
    data.getValue()
;;

**Comment by bryantrobbins** [comment]
Andriy and @mauricio1990silva were looking into this. Are we still on track with getting this into dg-commons by the end of the year?

**Comment by mibrahim** [comment]
@mauricio1990silva is it reasonable to assume that this will not happen before the end of the month ? I just want to plan for what features are going in Dec 15th

**Comment by mauricio1990silva** [comment]
I have done the code, I just need to correct a feww things, but sure this
can be fully done by Dec 15th

**Comment by mibrahim** [comment]
@mauricio1990silva any updates on that ?

**Comment by mibrahim** [comment]
@mauricio1990silva can you please send a PR if we're changing code ?
