### ISSUE TITLE
Hadoop example : Please insert the driver.sh 

### ISSUE THREAD

**Issue by vaibhash** [FINRAOS/DataGenerator#219]
I`m trying to follow the steps to run the hadoop example. Can somebody please provide the command to execute the example ?

**Comment by bryantrobbins** [comment]
We'll add some docs around this.

Our hesitation with including a "driver.sh" or similar is due to the Java code's tight coupling with a specific Hadoop version. What works on one cluster may not work on the next, etc.

Do you have a specific use case for DataGenerator at the moment, or just looking to play with the example?

**Comment by wnilkamal** [comment]
Assigning to @bryantrobbins to add documentation around Hadoop example.

**Comment by AayushiDwivedi** [comment]
@bryantrobbins we are just trying to run the hadoop example.

**Comment by mibrahim** [comment]
Do you have Hadoop installed ? you will definitely need a Hadoop environment to be able to run it. Let me know how can help, or if you have other ideas to improve it.

**Comment by vaibhash** [comment]
Hey @mibrahim, we are looking to run the tool from command line, we are using Docker based image(sequenceiq) and thus have Hadoop environment set up. We want to know the script to run the hadoop example as we want to see how much time it would take to generate large data set ( in range of 1Tb ), i.e. what content shall we put in driver.sh 

We want to run the tool from CLi rather than intelliJ and thus this query

**Comment by mibrahim** [comment]
You should be able to execute the example using the hadoop jar command:
https://hadoop.apache.org/docs/r1.0.4/commands_manual.html#jar
That means you have to copy your jar file (produced by mvn package) to your cluster edge/head node and execute the jar over there. I never tried to execute it over docker, I'll give it a try and let you know.
Docker would help you get a feel of how to run it, but won't be provide good measurements for performance. You need to run it over a sample of the machines you will be using in production.
Generally, for a fairly complicated problem that involves multiple tables generation, shaping the data with prior probability distributions we get about 1TB/hr using 20 amazon large instances.
That's not a rule of thumb, and the generation speed will depend on the complexity of your problem and the machines executing your models. I saw better results running on bare metal vs visualized environments, but again your mileage may vary.

**Comment by vaibhash** [comment]
Hey @mibrahim Thanks for the response. Yes, the intent of running on docker is to get a feel of tool. later we will try it on a actual full blown setup to do the bench-marking.

**Comment by AayushiDwivedi** [comment]
@mibrahim @wnilkamal 
We were able to run the example in Docker and also on our standalone Hadoop cluster. 
We used the following command to run the example:
`hadoop jar <main class jar path>  org/finra/datagenerator/samples/CmdLine -libjars ${LIBJARS} -i small_mr_sample.xml` 
LIBJARS contains the path to all the jar files.

Although the code runs without any error and a part-m-00000.gz file is also generated but the file itself is completely empty.
Another thing that I would like to add is that when we ran this example on IntelliJ, data was generated properly in the .gz files. 

Is there any obvious thing we are missing while running it through CLI?

**Comment by vaibhash** [comment]
@bryantrobbins @wnilkamal @mibrahim Hey guys, we are seeing this error while running the tool and thus tool is not generating ( or rather writing ) the data to the .gz file.

The error is as below ( highlighted main line )

**2015-07-01 18:09:06,220 ERROR [Thread-12] org.finra.datagenerator.consumer.DataConsumer: Error while reading: this/request/block from 4fdbcdc5cfa0:36359**
`
2015-07-01 18:09:06,221 ERROR [Thread-12] org.apache.hadoop.yarn.YarnUncaughtExceptionHandler: Thread Thread[Thread-12,5,main] threw an Exception.
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:453)
        at java.lang.Long.valueOf(Long.java:540)
        at org.finra.datagenerator.samples.manager.LineCountManager$LineCountBlock.buildFromResponse(LineCountManager.java:82)
        at org.finra.datagenerator.samples.consumer.SampleMachineConsumer.isExit(SampleMachineConsumer.java:114)
        at org.finra.datagenerator.samples.consumer.SampleMachineConsumer.consume(SampleMachineConsumer.java:138)
        at org.finra.datagenerator.distributor.multithreaded.DefaultDistributor.produceOutput(DefaultDistributor.java:129)
        at org.finra.datagenerator.distributor.multithreaded.DefaultDistributor.access$000(DefaultDistributor.java:37)
        at org.finra.datagenerator.distributor.multithreaded.DefaultDistributor$1.run(DefaultDistributor.java:89)
2015-07-01 18:09:07,178 INFO [main] org.finra.datagenerator.distributor.multithreaded.DefaultDistributor: DONE
`


This error originates from DataConsumer.java in function getResponse. Is there anything obvious we are missing ? Any troubleshooting steps you can recommend ?

**Comment by mibrahim** [comment]
I don't think you're missing anything, it seems like a bug. I'll go through the example this evening to make sure it still works and not broken & will let you know. Thanks for feedback.

**Comment by mibrahim** [comment]
@vaibhash & @AayushiDwivedi 

The pom.xml was missing the shade plugin to pack the dependencies & I also fixed the configuration to reuse the global configuration passed by the tool runner.

Since I had an open pull request, the code is still here for review ( @bryantrobbins & @mpeter28 can you review & merge ? ) :
https://github.com/FINRAOS/DataGenerator/pull/221

I used the same docker image you referred to, and the following are the steps to execute. Hope it helps, please let me know if you're still blocked.

```
# Put the SCXML XML samples on the HDFS
bash-4.1# ./usr/local/hadoop/bin/hadoop fs -put /mnt/dg-example-hadoop/src/main/resources/*.xml /

# Export the class path
bash-4.1# export HADOOP_CLASSPATH=/mnt/dg-example-hadoop/target/dg-example-hadoop-2.2-SNAPSHOT.jar

# Use the same uber jar in the libjars & execute
bash-4.1# ./usr/local/hadoop/bin/hadoop jar /mnt/dg-example-hadoop/target/dg-example-hadoop-2.2-SNAPSHOT.jar org.finra.datagenerator.samples.CmdLine -libjars /mnt/dg-example-hadoop/target/dg-example-hadoop-2.2-SNAPSHOT.jar -i /small_mr_sample.xml

.... Results will show here, be patient since it is running on docker ....

# list the result
bash-4.1# ./usr/local/hadoop/bin/hadoop fs -ls /user/root/brownbag_demo/dg-result/

# cat the result
bash-4.1# ./usr/local/hadoop/bin/hadoop fs -cat /user/root/brownbag_demo/dg-result/part-m-00000.gz | gunzip
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.7.0/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/mnt/dg-example-hadoop/target/dg-example-hadoop-2.2-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
A|1|2141052639|1070526319|null|null|null|null|null
A|2|418540263|209270131|null|null|null|null|null
A|3|-2032645687|-1016322843|null|null|null|null|null
B|1|-608101802|-304050901|null|null|null|null|null
B|2|-1701474394|-850737197|null|null|null|null|null
B|3|1535649676|767824838|null|null|null|null|null
C|1|2040440757|1020220378|null|null|null|null|null
C|2|478502367|239251183|null|null|null|null|null
C|3|-2022541728|-1011270864|null|null|null|null|null
```

**Comment by mibrahim** [comment]
forgot to mention that I mapped the project directory to /mnt in the docker exec instance:
```
docker run -v /home/<myhomedir>/projects/DataGenerator:/mnt sequenceiq/hadoop-docker:2.7.0
```

```
docker ps
docker exec -it d728c2323540 bash
```

**Comment by AayushiDwivedi** [comment]
@mibrahim Thanks a lot. It is working perfectly now.

**Comment by wnilkamal** [comment]
@AayushiDwivedi @vaibhash, we are curios as to what you guys are using the DataGenerator for? Would you mind sharing the use case you are using it (Whatever you can disclose that is)?

**Comment by bryantrobbins** [comment]
#221 includes the shade plugin fix for this. Will get this merged into master shortly.

**Comment by AayushiDwivedi** [comment]
@wnilkamal We are working on an analytics tool and need some in-house data to perform stress and load testing on the tool. We are using DataGenerator to create a variety of data for this purpose.

**Comment by mibrahim** [comment]
#221 got merged, closing.
