### ISSUE TITLE
Move JSON tool (used by website) into OSS repo

### ISSUE THREAD

**Issue by mibrahim** [FINRAOS/DataGenerator#228]
Review the library wrote by @mpeter28 .

@bryantrobbins 
@mikev37
@yukaReal

**Comment by bryantrobbins** [comment]
Question: what/how much of DG JSON tool code can be moved into common library?

**Comment by bryantrobbins** [comment]
Pending refactor of #238 . I'll ping @mpeter28 when this is ready

**Comment by bryantrobbins** [comment]
Module restructuring is not happening for 2.2.

But we can still check this into the repo. Need to make sure of libs and headers before 2.2 drop.

**Comment by mibrahim** [comment]
Closing. Will keep as a separate tool.
