### ISSUE TITLE
Update DG SCXML tool to support Spark Distributor

### ISSUE THREAD

**Issue by bryantrobbins** [FINRAOS/DataGenerator#234]
Acceptance Criteria:
* An SCXML model can be executed on Spark.

**Comment by bryantrobbins** [comment]
@Brijeshrpatel9 this is you!

**Comment by mibrahim** [comment]
@Brijeshrpatel9 should write an example that writes to an RDD beside the one the writes to files, then send a pull request to review. Thanks.

**Comment by bryantrobbins** [comment]
Basic implementation is done, but pending updates related to writing to RDD. @shraddha-patel looking into this.

Still targeted for 2.2.
