### ISSUE TITLE
dg:range more than 100 results in scientific notation number like 1E+2

### ISSUE THREAD

**Issue by mibrahim** [FINRAOS/DataGenerator#239]
Found by Srinivasan ( https://groups.google.com/forum/#!topic/datagenerator/-xOjfRq5MFs )

Quoted:
>			<state id="step1">
>				<onentry>
>					
>					<dg:assign name="var_1_1" set="Apple,Mango,Grapes,Papaya"/>
>
>					<dg:range name="var_1_2" from="1" to="1000" />
>					<dg:range name="var_1_3" from="0" to="9" step="1" />
>            
>				</onentry>
>				<transition event="end" target="end"/>
>			</state>
>
>    
>			<state id="end" />
>		</scxml>
>
>	For the range values greater than 100 I am getting values like 1E+1,2E+1 instead actual values like >1001,10003 .

**Comment by yukaReal** [comment]
Fixed. Thanks.
