### ISSUE TITLE
We should use EL to evaluate variables within SCXML models

### ISSUE THREAD

**Issue by bryantrobbins** [FINRAOS/DataGenerator#251]
https://docs.oracle.com/javaee/7/api/javax/el/package-summary.html

EL is a Java standard for expressions. We already use EL to evaluate conditions within the SCXML Engine. Can we expand this support so that some of these features are enabled via EL instead of custom syntax?

* Variable values (can variable values be assigned via expressions?)
* Macros (can macros become functions which the user can call in an expression?)
* Complex data types

EL would come with its own parsing and syntax as well.

**Comment by bryantrobbins** [comment]
Some additional thoughts:
* This would be a significant (breaking) change for existing code. Is there any chance for backward compatibility?
* What is the performance overhead of using EL?
* There is still value in having Java as the native/basic language for extension.
* Can we opt-in to pre-processing?

**Comment by mibrahim** [comment]
@mpeter28 thinking about how to express constraints. Add that to the additional thoughts at the top. We will decide later on the final direction.

**Comment by mibrahim** [comment]
Being replaced with 3.0 direction to use spark. @bryantrobbins ok with that ?
