### ISSUE TITLE
The %number macro does not interpret (precision, scale) consistent with ANSI SQL

### ISSUE THREAD

**Issue by jeanmusinski** [FINRAOS/DataGenerator#270]
Precision is the total number of the digits in a number. Scale is the number of digits to the right of the decimal point.

In dg-example-default, samplemachine.xml defines var_2_6 as expr="%number(5,2)". DG generates values such as 85829.40 and 61140.01. To be consistent with the ANSI definition, the generated values should be like 858.29 and 611.40

**Comment by mibrahim** [comment]
Tasks:
1. Update the docs at https://github.com/FINRAOS/DataGenerator/blob/master/docs/transformers/EquivalenceClass.rst
2. @leeny34 update the implementation of number to reflect the correct interpretation of precision / scale

References:
https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types#LanguageManualTypes-Decimals

**Comment by mibrahim** [comment]
Fixed by #272
