### ISSUE TITLE
The scxml header of the Eight Lonely Rooks example is not sufficient.

### ISSUE THREAD

**Issue by jeanmusinski** [FINRAOS/DataGenerator#271]
Currently, the scxml header of the Eight Lonely Rooks example is:
        <scxml xmlns="http://www.w3.org/2005/07/scxml"
               xmlns:cs="http://commons.apache.org/scxml"
               version="1.0" initial="start">

However, when running, the example throws: 
        org.xml.sax.SAXParseException; lineNumber: 12; columnNumber: 69; The prefix "dg" for element "dg:assign" is not bound.
 
The scxml header of the Eight Lonely Rooks example needs to include: 
        xmlns:dg="org.finra.datagenerator"

Also, the following may not be necessary:
        xmlns:cs="http://commons.apache.org/scxml"

**Comment by mibrahim** [comment]
fixed by #302
