### ISSUE TITLE
Compilation Error on JDK 1.8 1.8.0_72-b15

### ISSUE THREAD

**Issue by aosama** [FINRAOS/DataGenerator#274]
Cloned the repo and did mvn clean install
There is a compilation error in the Spark Distributor project
However on JDK 7 update 80 it compiles successfully
OR
Upgrading the SCALA version also solves the issue
http://stackoverflow.com/questions/24197836/compilation-failed-error-while-loading-annotatedelement-concurrentmap-charseq

Below is the compilation error on JDK8

--- scala-maven-plugin:3.2.1:compile (scala-compile-first) @ dg-spark ---
 Expected all dependencies to require Scala version: 2.10.0
 com.twitter:chill_2.10:0.5.0 requires scala version: 2.10.4
Multiple versions of scala libraries detected!
/home/aosama/NetBeansProjects/DataGenerator/dg-spark/src/main/code:-1: info: compiling
Compiling 7 source files to /home/aosama/NetBeansProjects/DataGenerator/dg-spark/target/classes at 1454199089281
error: error while loading CharSequence, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
error: error while loading ConcurrentMap, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/util/concurrent/ConcurrentMap.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 61)
error: error while loading Entry, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/util/Map$Entry.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
/home/aosama/NetBeansProjects/DataGenerator/dg-spark/src/main/code/org/finra/datagenerator/ScalaDataConsumer.scala:45: error: value getKey is not a member of java.util.Map.Entry[String,String]
      scalaDataPipe.getDataMap.put(ent.getKey, ent.getValue)
                                       ^
four errors found
------------------------------------------------------------------------
Reactor Summary:

Data Generator Parent POM ......................... SUCCESS [2.998s]
Data Generator Common Utils ....................... SUCCESS [18.751s]
Data Generator Core Library ....................... SUCCESS [14.169s]
Data Generator Example - Default Distributor ...... SUCCESS [1.998s]
Data Generator Example - HDFS Distributor ......... SUCCESS [5.951s]
Data Generator Simple CSV ......................... SUCCESS [2.223s]
Data Generator Example - Spark Distributor ........ FAILURE [3.747s]

**Comment by mibrahim** [comment]
Just rerun, should be able to pass

**Comment by yukaReal** [comment]
Now we have error on next step:

Results :

Failed tests:   testSendRequestSync(org.finra.datagenerator.consumer.DataConsumerTest): expected:<[test1]> but was:<[]>
  testSendRequestNoHandling(org.finra.datagenerator.consumer.DataConsumerTest): expected:<[test1]> but was:<[]>
  testSendRequestFromWriter(org.finra.datagenerator.consumer.DataConsumerTest): expected:<5> but was:<0>

Tests run: 195, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Data Generator Parent POM .......................... SUCCESS [  2.334 s]
[INFO] Data Generator Common Utils ........................ SUCCESS [ 34.288 s]
[INFO] Data Generator Core Library ........................ FAILURE [06:08 min]
[INFO] Data Generator Example - Default Distributor ....... SKIPPED
[INFO] Data Generator Example - HDFS Distributor .......... SKIPPED
[INFO] Data Generator Simple CSV .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by yukaReal** [comment]
Now it's compiled. Issue mentioned before is different - i'll create separate issue about it.
