### ISSUE TITLE
dg-common helpers are not dg specific

### ISSUE THREAD

**Issue by ShaneEbersole** [FINRAOS/DataGenerator#275]
There are a lot of Scala helpers which are not specific to DG, for instance DateHelper and IntHelper.  We should remove them, making sure there are no dependencies elsewhere in DG

@SamerAdra - please provide a list of the functions you want to remove as a comment to this issue

**Comment by SamerAdra** [comment]
Resolved by PR: https://github.com/FINRAOS/DataGenerator/pull/277
