### ISSUE TITLE
Test fails depending on network settings.

### ISSUE THREAD

**Issue by yukaReal** [FINRAOS/DataGenerator#292]
Depending on network settings 'testSendRequestSync' test fails or passes.

[http://stackoverflow.com/questions/1881546/inetaddress-getlocalhost-throws-unknownhostexception]:
It seems that InetAddress.getLocalHost() ignores the /etc/resolv.conf but only looks at the /etc/hosts file

This is changed in java 7 compare to java 6.

Log:
Results :

Failed tests:   testSendRequestSync(org.finra.datagenerator.consumer.DataConsumerTest): expected:<[test1]> but was:<[]>
  testSendRequestNoHandling(org.finra.datagenerator.consumer.DataConsumerTest): expected:<[test1]> but was:<[]>
  testSendRequestFromWriter(org.finra.datagenerator.consumer.DataConsumerTest): expected:<5> but was:<0>

Tests run: 195, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Data Generator Parent POM .......................... SUCCESS [  1.464 s]
[INFO] Data Generator Common Utils ........................ SUCCESS [ 16.370 s]
[INFO] Data Generator Core Library ........................ FAILURE [02:48 min]
[INFO] Data Generator Example - Default Distributor ....... SKIPPED
[INFO] Data Generator Example - HDFS Distributor .......... SKIPPED
[INFO] Data Generator Simple CSV .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by yukaReal** [comment]
See https://github.com/FINRAOS/DataGenerator/pull/293

**Comment by mibrahim** [comment]
Fixed and merged by #293
