### ISSUE TITLE
Compilation error at Example - HDFS Distributor by java 1.7

### ISSUE THREAD

**Issue by yukaReal** [FINRAOS/DataGenerator#294]
When we compile from java 1.7 we have error. No error for java 1.8.
Let's use java 1.8 for next version?

Log:

INFO] Reactor Summary:
[INFO] 
[INFO] Data Generator Parent POM .......................... SUCCESS [  5.137 s]
[INFO] Data Generator Common Utils ........................ SUCCESS [ 10.378 s]
[INFO] Data Generator Core Library ........................ SUCCESS [ 28.855 s]
[INFO] Data Generator Example - Default Distributor ....... SUCCESS [  2.666 s]
[INFO] Data Generator Example - HDFS Distributor .......... FAILURE [  0.747 s]
[INFO] Data Generator Simple CSV .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.003 s
[INFO] Finished at: 2016-03-11T19:14:03+00:00
[INFO] Final Memory: 46M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4:shade (default) on project dg-example-hadoop: Error creating shaded jar: Invalid signature file digest for Manifest main attributes -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

**Comment by yukaReal** [comment]
See https://github.com/FINRAOS/DataGenerator/pull/293

But it is still failing...

**Comment by dovidkopel** [comment]
We are no longer supporting Java 1.7, so this is no longer relevant.
