### ISSUE TITLE
State space explosion?

### ISSUE THREAD

**Issue by ptelang** [FINRAOS/DataGenerator#301]
I am trying to generate dataset with about 50 variables out of which about 25 are categorical variables. I am using "file" tag for specifying possible values for the 25 categorical variables. The rest of the variables are specified using "assign" tag. Each file for the 25 categorical variables contains less than 10 values. DG framework chokes for more than 11 variables. It appears to freeze; I let it run for over 15mins and it produced nothing and caused my computer's fan to run faster than I have ever seen before! I am running it in Eclipse on a Mac with 16GB RAM and 2.5 GHz i7 processor. 

Is there any solution for this issue?

**Comment by mpeter28** [comment]
State space explosion is definitely an issue, and we have a guide (https://github.com/FINRAOS/DataGenerator/blob/master/docs/SCXMLModelOptimization.rst) on working around that. Hopefully that helps!

**Comment by mibrahim** [comment]
In case you were putting all those states in a single node, consider splitting them into several nodes. DG attempts to compute the product of all variables in the same node before moving along. Most likely, that's the reason it's choking.

Please re-open if we didn't answer your question. Thanks,
