### ISSUE TITLE
Allow DataGenerator to Generate Data based off of another Model's dataset

### ISSUE THREAD

**Issue by SMxJrz** [FINRAOS/DataGenerator#47]
I don't think we've solved this one yet:

Suppose we wanted to generate a set of accounts, which contains some identifying information that is tied to that account (like an owner's name, birthday etc,.). 

We now want generate a set of transactions that tie the transactions to each account that we generated above. As it stands right now, we need to generate the set of accounts and generate the transactions using a custom consumer that parses through the account file.

Would like to see if it's possible to eliminate the need for consumers to handle parsing previously generated datasets, and move towards generating the two data sets side by side (if feasable)

#55

**Comment by bryantrobbins** [comment]
We have some docs on this now. One solution is to use pseudo-random number generators:
https://github.com/FINRAOS/DataGenerator/blob/master/docs/ConsistentValuesAcrossDependentModels.rst
