### ISSUE TITLE
We need standard way of postprocess data

### ISSUE THREAD

**Issue by yukaReal** [FINRAOS/DataGenerator#51]
One customer want to generate json data (to use it as mocks in testing his system)...

Maybe we can provide easy way to:
* export as json
* export as xml
* export to rational DB
* ...

**Comment by bryantrobbins** [comment]
These would be custom writers. They would need to take some type of argument specifying structure.

Is there still a request/need for these?

**Comment by bryantrobbins** [comment]
We are tracking this in #213 . Closing this one as dup
