### ISSUE TITLE
We need result analyser

### ISSUE THREAD

**Issue by yukaReal** [FINRAOS/DataGenerator#53]
Now we need to analysis / verify results manually.
It's easy to make a mistake in xml script and generate little bit different data set from desire one.

So, if we will have some kind of analysis tool, we will be able to analysis generated data and easy verify it.

Also we can use it for analysis generated data and external/original data to see difference.

**Comment by mibrahim** [comment]
The statistical tools ticket should be sufficient to cover the required function #174
