### ISSUE TITLE
We need to build set of standard data equivalence class generators

### ISSUE THREAD

**Issue by yukaReal** [FINRAOS/DataGenerator#54]
We have common data types, like:
* Date
* State
* Country
* Currency
* Market symbol
* Short random text
* Long random text (with spaces and so on)
* Phone
* Address
* zip code
* First Name, Last Name
* SSN
...

So, if it will be possible to use it inside xml configuration it will be really useful. Now it's necessary to create custom solutions.

**Comment by mibrahim** [comment]
part is in #180

**Comment by mibrahim** [comment]
@yukaReal can you visit this ?

**Comment by yukaReal** [comment]
Added:
* state
* stateShort
* country
* symbolNASDAQ
* symbolNotNASDAQ
* securityNameNASDAQ
* securityNameNotNASDAQ
See #180

**Comment by yukaReal** [comment]
We still have from initial list:
* Date
* Phone
* Address
* zip code
* First Name, Last Name

**Comment by yukaReal** [comment]
* Added 'phone' (with and without ext) and 'zip'.
* 'Date' has too name formats and requirements, so it's better to implement specially for every case especially.
* 'Address', first name and last name can be created by 'alphaWithSpaces' and 'alpha'.
IMHO, we done with this issue!
