### ISSUE TITLE
 Ability define expressions and calculations on nodes and edges.

### ISSUE THREAD

**Issue by wnilkamal** [FINRAOS/DataGenerator#60]
R1.4.8: Ability define expressions and calculations on nodes and edges. Expressions should be able to reference variable types described in R1.4.2 to R1.4.5.

R1.4.8.1: Simple mathematical expressions. (Add, Subtract, Divide, Multiply)
R1.4.8.2: Simple string manipulation. (Concatenate, Replace, Trim, Sub String, RegEx replace)

https://github.com/FINRAOS/DataGenerator/wiki/DataGenerator-V2-Requirements#r14-common-rules-for-r11-r12-and-r13

**Comment by bryantrobbins** [comment]
We currently support this on nodes via tags. Because any edge annotation can be trivially moved to a node, we'll stop there.
