### ISSUE TITLE
Ability define a database queries and simple flat files(R1.4.9.2) as a way to define variable assignments. 

### ISSUE THREAD

**Issue by wnilkamal** [FINRAOS/DataGenerator#61]
R1.4.9: Ability define a database queries(R1.4.9.1) and simple flat files(R1.4.9.2) as a way to define variable assignments. Look at the diagram below; the specification on the left is identical to the specification on the right. The only difference is the specification on the right is using a SQL query to define its dataset. Note the SQL can be replaced with a file URL which would contain the table/joined data in a CSV format.

https://github.com/FINRAOS/DataGenerator/wiki/DataGenerator-V2-Requirements#r14-common-rules-for-r11-r12-and-r13

**Comment by mibrahim** [comment]
Rest of the effort is tracked in #183
