### ISSUE TITLE
Implementation of all combinations and pairwise combinations within the dependency model 

### ISSUE THREAD

**Issue by wnilkamal** [FINRAOS/DataGenerator#63]
Implementation of **all combinations** and **pairwise combinations** within the dependency model.

Refer to section R1.4.20(1.4.20.1 , 1.4.20.2 and1.4.20.3) in https://github.com/FINRAOS/DataGenerator/wiki/DataGenerator-V2-Requirements#r14-common-rules-for-r11-r12-and-r13

**Comment by mibrahim** [comment]
We implemented n-wise tag, without compaction.
